name: Test, Build and Deploy

on:
  push

jobs:
  build:
    if: "(!contains(github.event.commits[0].message, '[skip ci]')) && (!contains(github.event.commits[0].message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Test for voices 👓
        run:
          npm run test-voice

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
      
      - name: Upload build result for deploy 🔼
        uses: actions/upload-artifact@v1
        if: "(github.ref == 'refs/heads/master') && (!contains(github.event.commits[0].message, '[skip build]')) && (!contains(github.event.commits[0].message, '[build skip]'))"
        with:
          name: dist
          path: dist

  deploy:
    if: "(github.ref == 'refs/heads/master') && (!contains(github.event.commits[0].message, '[skip build]')) && (!contains(github.event.commits[0].message, '[build skip]'))"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build result 🔽
        uses: actions/download-artifact@v1
        with:
          name: dist
      
      - name: Remove old artifacts 🗑️
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
          skip-tags: true

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PRODUCTON_KEY }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: dist
